name: Deploy to Render.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.17.1"

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to Render.com
        env:
          RENDER_EMAIL: andrejnovi1133@gmail.com
          RENDER_PASSWORD: Ibegyourpardon
          RENDER_PROJECT_NAME: locations-hometask
        run: |
          curl -X POST https://api.render.com/v1/deploys \
            -d "branch=main" \
            -d "publicEnv=RENDER_EMAIL=$RENDER_EMAIL" \
            -d "publicEnv=RENDER_PASSWORD=$RENDER_PASSWORD" \
            -d "publicEnv=RENDER_PROJECT_NAME=$RENDER_PROJECT_NAME" \
            -d "buildCommand=npm run build"
